backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'releases'
    label: 'Releases'
    folder: 'content/releases'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Release Title', name: 'releasetitle', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'IMDb Link', name: 'imdblink', widget: 'string' }
      - { label: "Era", name: "era", widget: "select", options: ["The High Republic", "The Fall of the Jedi", "Reign of the Empire", "Age of Rebellion", "The New Republic", "Rise of the First Order"] }
      - { label: 'Year', name: 'year', widget: "number", default: 1, value_type: "int" }
  
  